spring:
  application:
    name: Spring Boot With GraphQL
  graphql.graphiql.enabled: true
  datasource:
    name: H2 DB Connection
    url: jdbc:h2:mem:localdb;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     open-in-view: false
     show-sql: true
     defer-datasource-initialization: true
     hibernate:
       ddl-auto: 'create-drop'
